#!/bin/bash
#DECLARACIÓN DE VARIABLES

#PARA CREAR PROYECTO

echo "ASIGNAR NOMBRE AL PROYECTO: "
#read PROYECTO_NOMBRE
echo "Creando..."

PROYECTO_NOMBRE=testa
PROYECTO_PATH=/home/violeta/studying/CYBERSEGURIDAD/BASTI/MOVILES/practica/${PROYECTO_NOMBRE}
TARGET=1
ACTIVITY=Activity
DOM1=com
DOM2=mipractica
DOM3=miandroid

#PARA CREAR KEYSTORE CON RSA
VALIDITY=10000
CN=violeta
L=leon
S=spain
C=ES
STOREPASS=111111
KEYPASS=222222
ALIAS=PROYECTO_NOMBRE_Key

#PARA CREAR R.java

ANDROID_DIRECTORIO=/home/violeta/studying/CYBERSEGURIDAD/BASTI/MOVILES/practica/android-sdk-linux
ANDROID_PLATFORM=android-23

#PARA COMPILAR
SEP=\:

#*************************************************
#LANZAR LOS COMANDOS 

#CREAR PROYECTO_PATH
android create project --target ${TARGET} --name ${PROYECTO_NOMBRE} --path ${PROYECTO_PATH} --activity ${ACTIVITY} --package ${DOM1}.${DOM2}.${DOM3}

#ENTRAR EN EL DIRECTORIO DEL PROYECTO Y AÑADIR DIRECTORIO /obj 
cd ${PROYECTO_NOMBRE}
mkdir obj

#EDITAR MAIN
echo "EDITAR main.xml"
#read
#vim ${PROYECTO_PATH}/res/layout/main.xml
cp ${PROYECTO_PATH}/../apProFiles/main.xml ${PROYECTO_PATH}/res/layout/main.xml
cp ${PROYECTO_PATH}/../apProFiles/row.xml ${PROYECTO_PATH}/res/layout/row.xml

# EDITAR MANIFEST
echo "EDITAR AndroidManifest.xml"
#read
#vim ${PROYECTO_PATH}/AndroidManifest.xml
cp ${PROYECTO_PATH}/../apProFiles/AndroidManifest.xml ${PROYECTO_PATH}/AndroidManifest.xml

#CREAR KEYSTORE
echo "Generando keystore..."

keytool -genkeypair -validity ${VALIDITY} -dname "CN=${CN},L=${L},S=${S},C=${C}" -keystore ${PROYECTO_NOMBRE}.keystore -storepass ${STOREPASS} -keypass ${KEYPASS} -alias ${ALIAS} -keyalg RSA -v

# -- ESCRIBIR JAVA APPLICATION CODE --
echo "ESCRIBIR PROGRAMA DE LA APLI EN JAVA"
#read
#vim ${PROYECTO_PATH}/src/${DOM1}/${DOM2}/${DOM3}/$APLI_PROGRAMA
cp ${PROYECTO_PATH}/../apProFiles/apli_programa.java ${PROYECTO_PATH}/src/${DOM1}/${DOM2}/${DOM3}/$APLI_PROGRAMA
cp ${PROYECTO_PATH}/../apProFiles/Test.java ${PROYECTO_PATH}/src/${DOM1}/${DOM2}/${DOM3}/Test.java

# -- DECLARAR RECURSOS --
#echo "DECLARAR RECURSOS EN res/values/strings.xml"
#read
#vim ${PROYECTO_PATH}/res/values/strings.xml

#CREAR R.java
echo "Creando R.java..."
aapt package -v -f -m -S ${PROYECTO_PATH}/res -J ${PROYECTO_PATH}/src -M ${PROYECTO_PATH}/AndroidManifest.xml -I ${ANDROID_DIRECTORIO}/platforms/${ANDROID_PLATFORM}/android.jar 

#COMPILAR
echo "Compilando..."
javac -verbose -d ${PROYECTO_PATH}/obj/ -classpath ${ANDROID_DIRECTORIO}/platforms/${ANDROID_PLATFORM}/android.jar${SEP}${PROYECTO_PATH}/obj -sourcepath ${PROYECTO_PATH}/src ${PROYECTO_PATH}/src/${DOM1}/${DOM2}/${DOM3}/*.java

#CREAR DEX ARCHIVO
echo "Creando archivo dex..."
dx --dex --verbose --output=${PROYECTO_PATH}/bin/classes.dex ${PROYECTO_PATH}/obj/ ${PROYECTO_PATH}/libs/

#CREAR APK ARCHIVO 
echo "Creando archivo apk..."
aapt package -v -f -M ${PROYECTO_PATH}/AndroidManifest.xml -S ${PROYECTO_PATH}/res -I ${ANDROID_DIRECTORIO}/platforms/${ANDROID_PLATFORM}/android.jar -F ${PROYECTO_PATH}/bin/${PROYECTO_NOMBRE}.unsigned.apk ${PROYECTO_PATH}/bin

#SIGN APK ARCHIVO
echo "Firmando proyecto..."
jarsigner -verbose -keystore ${PROYECTO_PATH}/${PROYECTO_NOMBRE}.keystore -storepass $STOREPASS -keypass $KEYPASS -signedjar ${PROYECTO_PATH}/bin/${PROYECTO_NOMBRE}.signed.apk ${PROYECTO_PATH}/bin/${PROYECTO_NOMBRE}.unsigned.apk ${ALIAS}

#ZIP-ALIGN APK ARCHIVO
echo "Zip-alineando..."
zipalign -v -f 4 ${PROYECTO_PATH}/bin/${PROYECTO_NOMBRE}.signed.apk ${PROYECTO_PATH}/bin/${PROYECTO_NOMBRE}.apk

# -- START EMULATOR --

#emulator -wipe-data -avd MySonyEricsson

#INSTALL IN EMULATOR

#adb -e install bin/${PROYECTO_NOMBRE}.apk

#UNINSTALL
#adb shell rm /data/app/${DOM1}.${DOM2}.${DOM3}.apk

#***************
#CREAR EMULATOR
#android --verbose create avd --name MySonyEricsson --target ${ANDROID_PLATFORM} --sdcard 1024M --abi default/x86_64
#emulator -wipe-data -avd MySonyEricsson
